
###Obtener una lista de plazas de estacionamientos
GET http://localhost:8080/api/parking-spots

### Obtener una plaza estacionamiento por id
GET http://localhost:8080/api/parking-spots/1


### Crear una nueva plaza de aparcamiento
POST http://localhost:8080/api/parking-spots
Content-Type: application/json

{
  "code": "5A",
  "available": 2
}

